# Generated by Django 3.0.8 on 2020-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200802_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
