# Generated by Django 3.0.8 on 2020-08-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_pe_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
