# Generated by Django 3.0.8 on 2020-09-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='one_month_percentage_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='one_week_percentage_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='one_year_percentage_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
