# Generated by Django 3.0.8 on 2020-09-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20200911_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(),
        ),
    ]
